import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Web Store</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Web Store
                </h1>

                <p className={styles.description}>
                    ECommerce Store
                </p>

                <div className={styles.grid}>
                    <a href="#" className={styles.card}>
                        <h2>Product #1</h2>
                        <p>Product #1 Description</p>
                    </a>

                    <a href="#" className={styles.card}>
                        <h2>Product #2</h2>
                        <p>Product #2 Description</p>
                    </a>

                    <a
                        href="#"
                        className={styles.card}
                    >
                        <h2>Product #3</h2>
                        <p>Product #3 Description</p>
                    </a>

                    <a
                        href="#"
                        className={styles.card}
                    >
                        <h2>Product #4</h2>
                        <p>
                            Product #4 Description
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                Powered by Web Store
            </footer>
        </div>
    )
}

export default Home
